version: '3.1'

services:
        db:
                image: postgres
                environment:
                        POSTGRES_PASSWORD: testpwd
                        POSTGRES_USER: testuser
                        POSTGRES_DB: testdb
                ports:
                        - '5432:5432'
                volumes:
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
